// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: o377HB3bFr4ZkQwQAbxSoD

import * as React from "react";
import { hasVariant, ensureGlobalVariants } from "@plasmicapp/react-web";
import { AntdConfigProvider } from "@plasmicpkgs/antd5/skinny/registerConfigProvider";
import { Web3GlobalContext } from "suinova-nft-builder/dist/index.js";

export interface GlobalContextsProviderProps {
  children?: React.ReactElement;
  antdConfigProviderProps?: Partial<
    Omit<React.ComponentProps<typeof AntdConfigProvider>, "children">
  >;
  web3GlobalContextProps?: Partial<
    Omit<React.ComponentProps<typeof Web3GlobalContext>, "children">
  >;
}

export default function GlobalContextsProvider(
  props: GlobalContextsProviderProps
) {
  const { children, antdConfigProviderProps, web3GlobalContextProps } = props;

  return (
    <AntdConfigProvider
      {...antdConfigProviderProps}
      borderRadius={
        antdConfigProviderProps && "borderRadius" in antdConfigProviderProps
          ? antdConfigProviderProps.borderRadius!
          : 6
      }
      colorBgBase={
        antdConfigProviderProps && "colorBgBase" in antdConfigProviderProps
          ? antdConfigProviderProps.colorBgBase!
          : "#ffffff"
      }
      colorError={
        antdConfigProviderProps && "colorError" in antdConfigProviderProps
          ? antdConfigProviderProps.colorError!
          : "#ff4d4f"
      }
      colorInfo={
        antdConfigProviderProps && "colorInfo" in antdConfigProviderProps
          ? antdConfigProviderProps.colorInfo!
          : "#1677ff"
      }
      colorPrimary={
        antdConfigProviderProps && "colorPrimary" in antdConfigProviderProps
          ? antdConfigProviderProps.colorPrimary!
          : "#1677ff"
      }
      colorSuccess={
        antdConfigProviderProps && "colorSuccess" in antdConfigProviderProps
          ? antdConfigProviderProps.colorSuccess!
          : "#52c41a"
      }
      colorWarning={
        antdConfigProviderProps && "colorWarning" in antdConfigProviderProps
          ? antdConfigProviderProps.colorWarning!
          : "#faad14"
      }
      controlHeight={
        antdConfigProviderProps && "controlHeight" in antdConfigProviderProps
          ? antdConfigProviderProps.controlHeight!
          : 32
      }
      defaultDark={
        antdConfigProviderProps && "defaultDark" in antdConfigProviderProps
          ? antdConfigProviderProps.defaultDark!
          : false
      }
      lineWidth={
        antdConfigProviderProps && "lineWidth" in antdConfigProviderProps
          ? antdConfigProviderProps.lineWidth!
          : 1
      }
      loadingText={
        antdConfigProviderProps && "loadingText" in antdConfigProviderProps
          ? antdConfigProviderProps.loadingText!
          : undefined
      }
      removeLoading={
        antdConfigProviderProps && "removeLoading" in antdConfigProviderProps
          ? antdConfigProviderProps.removeLoading!
          : undefined
      }
      sizeStep={
        antdConfigProviderProps && "sizeStep" in antdConfigProviderProps
          ? antdConfigProviderProps.sizeStep!
          : 4
      }
      sizeUnit={
        antdConfigProviderProps && "sizeUnit" in antdConfigProviderProps
          ? antdConfigProviderProps.sizeUnit!
          : 4
      }
      themeStyles={
        antdConfigProviderProps && "themeStyles" in antdConfigProviderProps
          ? antdConfigProviderProps.themeStyles!
          : true
          ? {
              fontFamily: "Roboto",
              fontSize: "16px",
              fontWeight: "400",
              lineHeight: "1.5",
              color: "#535353",
              letterSpacing: "normal"
            }
          : undefined
      }
      wireframe={
        antdConfigProviderProps && "wireframe" in antdConfigProviderProps
          ? antdConfigProviderProps.wireframe!
          : false
      }
    >
      <Web3GlobalContext
        {...web3GlobalContextProps}
        contractPackageId={
          web3GlobalContextProps &&
          "contractPackageId" in web3GlobalContextProps
            ? web3GlobalContextProps.contractPackageId!
            : "0x2d99da054514ff31c7e7da82751d11bb16b53c66290c435a409e17c8992e35ed"
        }
        createdCollection={
          web3GlobalContextProps &&
          "createdCollection" in web3GlobalContextProps
            ? web3GlobalContextProps.createdCollection!
            : "6fb31c5e-0ba7-401e-a788-8e87d65cff35"
        }
        importedCollection={
          web3GlobalContextProps &&
          "importedCollection" in web3GlobalContextProps
            ? web3GlobalContextProps.importedCollection!
            : "0x847d5967dccc496ef9f5dc3673f1e7d174743fbd9d9e29e8c54c33eb74d912d5"
        }
        mintingInfo={
          web3GlobalContextProps && "mintingInfo" in web3GlobalContextProps
            ? web3GlobalContextProps.mintingInfo!
            : {
                id: "6fb31c5e-0ba7-401e-a788-8e87d65cff35",
                projectId: "o377HB3bFr4ZkQwQAbxSoD",
                collectionId:
                  "0xed190d47d4eca965497fbcbd4a46e6348ccfe5564e1cb9e121d8045b48cbee8b",
                admin:
                  "0x7c484896d088f2eb3012cac48de62fd4ec02c54540cbb1cd5e312e02216d055a",
                name: "Sui NoVa demo 1",
                description:
                  "Embark on a Cosmic Journey with Magic Astronauts! \ud83d\ude80\u2728\nWelcome to the Magic Astronauts NFT collection\u2014a mesmerizing fusion of space exploration and ethereal wonder! Each Magic Astronaut is a unique digital masterpiece, blending futuristic space gear with mystical elements that capture the boundless imagination of the cosmos.",
                imageUrl:
                  "https://s3-development-25.s3.ap-southeast-1.amazonaws.com/15278e7b836bbd7c83e48abbb095c56a.png",
                royaltyFee: "0",
                hasPresale: false,
                whitelistStartTime: "1748565740",
                whitelistEndTime: "0",
                presaleStartTime: "1748565740",
                presaleEndTime: "0",
                presaleNftPrice: "0",
                presaleWhitelistedUsers: [],
                presaleTotalNft: "0",
                presaleNftPerUser: "0",
                publicSaleStartTime: "1748565740",
                publicSaleEndTime: "0",
                publicNftPrice: "0",
                nftPerUser: "0",
                totalSupply: "0",
                mintedSupply: "0",
                status: "ACTIVE",
                createdAt: "2025-05-29T16:42:20.629Z",
                updatedAt: "2025-05-29T16:42:27.538Z",
                items: [
                  {
                    id: "65",
                    launchpadId: "6fb31c5e-0ba7-401e-a788-8e87d65cff35",
                    name: "Sui Nova demo 1",
                    description:
                      "Unique Artworks: 1,000 one-of-a-kind NFTs, each featuring a Magic Astronaut with distinct traits, suits, and cosmic backgrounds.",
                    imageUrl:
                      "https://s3-development-25.s3.ap-southeast-1.amazonaws.com/15278e7b836bbd7c83e48abbb095c56a.png",
                    attributes: [
                      { value: "red", trait_type: "background" },
                      { value: "gray", trait_type: "background" },
                      { value: "black", trait_type: "background" }
                    ],
                    creator:
                      "0x7c484896d088f2eb3012cac48de62fd4ec02c54540cbb1cd5e312e02216d055a",
                    createdAt: "2025-05-29T16:42:20.641Z",
                    updatedAt: "2025-05-29T16:42:20.641Z"
                  }
                ],
                visions: [
                  {
                    id: "36",
                    launchpadId: "6fb31c5e-0ba7-401e-a788-8e87d65cff35",
                    description: "milestone 1",
                    visionTime: "2025-05-30T00:40:19.549Z",
                    createdAt: "2025-05-29T16:42:20.650Z",
                    updatedAt: "2025-05-29T16:42:20.650Z"
                  },
                  {
                    id: "37",
                    launchpadId: "6fb31c5e-0ba7-401e-a788-8e87d65cff35",
                    description: "milestone 2",
                    visionTime: "2025-05-31T00:40:20.000Z",
                    createdAt: "2025-05-29T16:42:20.650Z",
                    updatedAt: "2025-05-29T16:42:20.650Z"
                  },
                  {
                    id: "38",
                    launchpadId: "6fb31c5e-0ba7-401e-a788-8e87d65cff35",
                    description: "milestone 3",
                    visionTime: "2025-06-01T00:40:28.000Z",
                    createdAt: "2025-05-29T16:42:20.650Z",
                    updatedAt: "2025-05-29T16:42:20.650Z"
                  }
                ],
                teams: [
                  {
                    id: "39",
                    launchpadId: "6fb31c5e-0ba7-401e-a788-8e87d65cff35",
                    memberName: "Member1",
                    memberTitle: "Manager",
                    createdAt: "2025-05-29T16:42:20.659Z",
                    updatedAt: "2025-05-29T16:42:20.659Z"
                  },
                  {
                    id: "40",
                    launchpadId: "6fb31c5e-0ba7-401e-a788-8e87d65cff35",
                    memberName: "Member2",
                    memberTitle: "CEO",
                    createdAt: "2025-05-29T16:42:20.659Z",
                    updatedAt: "2025-05-29T16:42:20.659Z"
                  },
                  {
                    id: "41",
                    launchpadId: "6fb31c5e-0ba7-401e-a788-8e87d65cff35",
                    memberName: "Member3",
                    memberTitle: "CTO",
                    createdAt: "2025-05-29T16:42:20.659Z",
                    updatedAt: "2025-05-29T16:42:20.659Z"
                  }
                ]
              }
        }
      >
        {children}
      </Web3GlobalContext>
    </AntdConfigProvider>
  );
}
